### ISSUE TITLE
Indirect memory access

### ISSUE THREAD

**Issue by neoneye** [neoneye/loda-lab#9]
I have not yet implemented the dollar dollar syntax. Example `mov $0, $$0`.

As of 7 sep 2021, there are around 50 loda programs that use indirect memory access.

**Comment by ckrause** [comment]
This would be very valuable. Example here: https://loda-lang.org/edit/?oeis=A41

**Comment by neoneye** [comment]
Yes, I'm working on it in [this branch](https://github.com/loda-lang/loda-rust/compare/develop...feature/indirect_memory_access_hashmap_instead_of_register_vec).

Status as of 20-sep-2022. 

LODA programs that use indirect can be evaluated and works in most cases.

Indirect also works in the LODA-RUST miner.

I have not tried it in the webclient, but I think it works.

TODO: With huge numbers, then the mechanism for checking numbers, isn't working. The Semantics class has to be a template, either with limits-enabled, or unlimited. This is tricky.

TODO: Migrate semantics tests, to exercise the Semantics class. I don't think there is any problems in it.

TODO: The `lpb` instruction prepare for using indirect. I don't think there is any problems in it.

**Comment by neoneye** [comment]
Now indirect memory access is working in the web editor, and the miner.
